site_name: Vector Documentation
copyright: Copyright &copy; 2019-2020 Randall Maas and team
repo_url: https://github.com/randym32/Anki.Vector.Documentation
repo_name: Vector Community Documents
edit_uri: edit/master/documents/

theme:
  name: material
  custom_dir: theme
  features:
    - search.suggest
    - navigation.instant
    - navigation.sections
    - navigation.expand

use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - meta

docs_dir: documents
extra:
  generator: false
extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      prebuild_index: true
  - localsearch
